[build-system]
requires = ["setuptools >= 61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "foraging"
version = "0.1.0"
description = "Package for analyzing behavior and beliefs in POMDP foraging task"
authors = [
    {name = "Noushin Quazi"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy (>=2.2.3,<3.0.0)",
    "matplotlib (>=3.10.1,<4.0.0)",
    "seaborn (>=0.13.2,<0.14.0)",
    "pandas (>=2.2.3,<3.0.0)",
    "scipy (>=1.15.2,<2.0.0)",
    "tqdm (>=4.67.1,<5.0.0)",
    "statsmodels (>=0.14.4,<0.15.0)",
    "python-dotenv (>=1.1.0,<2.0.0)",
    "kneed (>=0.8.5,<0.9.0)",
    "h5py (>=3.13.0,<4.0.0)",
    "scikit-learn (>=1.6.1,<2.0.0)",
    "openpyxl (>=3.1.5,<4.0.0)",
    "tabulate (>=0.9.0,<0.10.0)",
    "notebook (>=7.4.1,<8.0.0)",
    "jupytext (>=1.17.2,<2.0.0)"
]

[project.optional-dependencies]
dev = [
    "polars (>=1.26.0,<2.0.0)",
    "rich (>=13.9.4,<14.0.0)"
]

[tool.unidep]
channels = ['conda-forge']
project_dependency_handling = "same-name"
keywords = ['foraging', 'primates', 'behavioral analysis', 'POMDP']